[settings]
trusted_config_paths = [
    '~/khan/webapp',
    '~/khan/frontend',
    '~/khan/perseus',
    '~/khan/wonder-blocks',
    '~/khan/wonder-stuff',
    '~/khan/event-schemas',
    '~/khan/devtools/our-lovely-cli',
]

[tools]
# NOTE: We don't use `mise` to manage `pnpm`.  Instead each repo has a
# `packageManager` field in its package.json that specifies the version
# of `pnpm` to use.  `node` will no longer be shipping `corepack` in
# version 25 so we will need to update this config to include `pnpm` at
# that point.
node = "20.20"
