apiVersion: v1
kind: Pod
metadata:
  name: &service-name khandev
spec:
  volumes:
  - name: khandev-volume
    persistentVolumeClaim:
      claimName: khandev-claim
  containers:
  - name: *service-name
    image: kabuild-image
    volumeMounts:
    - mountPath: "/home/khandev/khan"
      name: khandev-volume
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 4096Mi
        cpu: 1000m
  restartPolicy: Never
