apiVersion: v1
kind: Pod
metadata:
  name: &service-name kabuild
spec:
  volumes:
  - name: kabuild-volume
    persistentVolumeClaim:
      claimName: kabuild-claim
  containers:
  - name: *service-name
    image: kabuild-image
    volumeMounts:
    - mountPath: "/data"
      name: kabuild-volume
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 1024Mi
        cpu: 500m
  restartPolicy: Never

  # TODO(ebrown): Should NOT need service accountname
  serviceAccountName: stage1-ksa
