kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kabuild-claim
spec:
  storageClassName: kabuild-spin-retain
  resources:
    requests:
      storage: 6Gi
  accessModes:
    - ReadWriteOnce
---
# This storage class overrides standard-rwo to force Retain=true
# Thus, data sticks around.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kabuild-spin-retain
provisioner: kubernetes.io/gce-pd
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
