apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: kabuild
build:
  artifacts:
  - image: kabuild-image
    docker:
      dockerfile: containers/kabuild/Dockerfile
    context: ../..
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - k8s.yaml
portForward:
- resourceType: Pod
  port: 8088
- resourceType: Pod
  port: 2000
profiles:
- name: cloudbuild
  build:
    googleCloudBuild:
      projectId: khan-internal-services
