apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: kabuild
build:
  artifacts:
  - image: kabuild-image
    docker:
      dockerfile: containers/kabuild/Dockerfile
    context: ../..
  tagPolicy:
    gitCommit: {}
profiles:
- name: cloudbuild
  build:
    googleCloudBuild:
      projectId: khan-internal-services
